# Ruby CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/ruby:2.5.0

references:
  attach_code_workspace: &attach_code_workspace
    attach_workspace:
      at: ~/repo

  restore_bundle_dependencies: &restore_bundle_dependencies
    run:
      name: Restore bundle dependencies from workspace
      command: bundle --path vendor/bundle

jobs:
  checkout_and_bundle:
    <<: *defaults
    steps:
      - checkout
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - persist_to_workspace:
          root: .
          paths: .

  rspec:
    <<: *defaults
    steps:
      - *attach_code_workspace
      - *restore_bundle_dependencies
      - run: bundle exec rspec

  vulnerability_check:
    <<: *defaults
    steps:
      - *attach_code_workspace
      - *restore_bundle_dependencies
      - run: bundle exec bundle-audit update && bundle exec bundle-audit check

workflows:
  version: 2
  build:
    jobs:
      - checkout_and_bundle:
          context: wealthsimple
      - rspec:
          context: wealthsimple
          requires:
            - checkout_and_bundle
      - vulnerability_check:
          context: wealthsimple
          requires:
            - checkout_and_bundle

  security-audit:
    triggers:
      - schedule:
          # 11:50 am UTC: 6:50 am EST / 7:50 am EDT
          cron: "50 11 * * *"
          filters:
            branches:
              only: master
    jobs:
      - checkout_and_bundle:
          context: wealthsimple
      - vulnerability_check:
          context: wealthsimple
          requires:
            - checkout_and_bundle
